### PR TITLE
allow running commands from neo-tree

### PR DESCRIPTION
**Pull request by gbprod**
Ref: #25

### CODE REVIEW

**Comment by foobar1643** [comment]
While running `lua require('phpactor').rpc('new_class')` I get:

```
E5108: Error executing lua ...cal/share/nvim/lazy/phpactor.nvim/lua/phpactor/utils.lua:34: attempt to index field 'tree' (a nil value)
stack traceback:
        ...cal/share/nvim/lazy/phpactor.nvim/lua/phpactor/utils.lua:34: in function 'path'
        ...cal/share/nvim/lazy/phpactor.nvim/lua/phpactor/utils.lua:40: in function 'folder'
        ...im/lazy/phpactor.nvim/lua/phpactor/handler/new_class.lua:6: in function 'handler'
        ...lt/.local/share/nvim/lazy/phpactor.nvim/lua/phpactor.lua:75: in function 'rpc'
        [string ":lua"]:1: in main chunk
```

**Comment by foobar1643** [comment]
[This](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/309#issuecomment-1101862659) might explain why the error happens. I think netrw mode has its own window ID which is why the default tree is nil.

**Comment by gbprod** [comment]
Thanks for your feedback @foobar1643, this should be better now :)

**Comment by gbprod** [comment]
Seems to work great for me, I'll merge this, if you have any feedback @foobar1643 , feel free to open an issue/PR :)

**Comment by rodnaph** [comment]
This change has caused a regression for me...

https://github.com/gbprod/phpactor.nvim/commit/8c735746d1ecdda42c1034b87e314a6af6e2e9a7#diff-75dcee4b4d73302a31c7e2e40ea021d516beb9162689ece771933e98f9ecef4dR50

`attempt to call field 'get_clients' (a nil value)`

Looks like my neovim is too old, as this was changed here...

https://github.com/neovim/neovim/pull/24113

FYI to anyone else running into this issue.

**Comment by gbprod** [comment]
oh! thanks, maybe it's too soon to change this call, i'll fix it

**Comment by gbprod** [comment]
@rodnaph should be fixed now

**Pull request merged**
